name: Deploy to S3

on:
  push:
    branches:
      - main  # Or whichever branch you want to trigger deployments from

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies and build
      run: |
        npm install --legacy-peer-deps
        CI=false npm run build
      env:
        NODE_OPTIONS: --max-old-space-size=4096  # Correctly placed in the build step


    - name: Deploy to S3
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.S3_BUCKET_NAME }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'us-west-2'  # or your AWS region
        SOURCE_DIR: 'build'
        REACT_APP_API_URL: 'http://api.nimblebee.io'
