name: Deploy to Azure

on:
  workflow_dispatch:  # Allow manual triggering from GitHub UI
  push:
    branches:
      - main  # Only trigger on push to the 'main' branch

jobs:
  build:
    # Ensure the job only runs on manual trigger or push to the 'main' branch
    if: ${{ github.event_name == 'workflow_dispatch' || github.ref_name == 'main' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Cache Node.js modules
        id: cache-node-modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install yarn
        run: npm install -g yarn

      - name: Install dependencies
        run: yarn install
        if: steps.cache-node-modules.outputs.cache-hit != 'true'

      - name: Build image
        run: |
          yarn build
        env:
          SENTRY_AUTH_TOKEN: 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

      - name: Zip artifact for deployment
        run: (cd ./.next/standalone && zip -r ../../release.zip .)

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    # Ensure deployment only runs on manual trigger or push to the 'main' branch
    if: ${{ github.event_name == 'workflow_dispatch' || github.ref_name == 'main' }}
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write  # Required for JWT authentication

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_4405A45699474090BBF161078DF725FB }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_CF2241290AE3402CB767D18D2E330330 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_F63FCF82167448FDAB2D87D1A5A3CCE9 }}

      - name: Upload static files to Azure Blob Storage
        run: |
          az storage blob sync -c 'nimblebee-front-static' --account-name nimblebeefrontstorage --account-key ${{ secrets.AZURE_STORAGE_ACCOUNT_KEY }} -s './.next/static' -d '_next/static'
          az storage blob sync -c 'nimblebee-front-static' --account-name nimblebeefrontstorage --account-key ${{ secrets.AZURE_STORAGE_ACCOUNT_KEY }} -s './public' -d 'public'
        continue-on-error: true

      - name: Purge Azure CDN endpoint
        run: |
          az cdn endpoint purge --content-paths '/*' --profile-name nimblebee-front-cdn --name nimblebee-front-cdn --resource-group nimblebee-front_group
        continue-on-error: true

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'nimblebee-front'
          slot-name: 'production'
          package: .
