name: Deploy to Azure

on:
  workflow_dispatch:  # Allow manual triggering from GitHub UI
  push:
    branches:
      - main  # Trigger only on push to the 'main' branch

jobs:
  build:
    if: ${{ github.event_name == 'workflow_dispatch' || github.ref_name == 'main' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install Yarn
        run: npm install -g yarn

      - name: Build Image
        run: |
          yarn install
          yarn build
        env:
          SENTRY_AUTH_TOKEN: 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

  test:
    if: ${{ github.event_name == 'workflow_dispatch' || github.ref_name == 'main' }}
    runs-on: ubuntu-latest
    needs: build  # Ensure tests run only after the build job completes

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install Cypress
        run: npm install cypress --save-dev --legacy-peer-deps

      # Nginx Setup for Subdomain Routing
      - name: Install Nginx
        run: sudo apt-get update && sudo apt-get install -y nginx

      - name: Configure Nginx for Subdomain Routing
        run: |
          echo "
          server {
            listen 80;
            server_name www.nimblebee.local;
            location / {
              proxy_pass http://localhost:3000;
              proxy_set_header Host \$host;
              proxy_set_header X-Real-IP \$remote_addr;
            }
          }
          " | sudo tee /etc/nginx/sites-available/default

      - name: Restart Nginx to Apply Configuration
        run: sudo service nginx restart

      - name: Start Application for Testing
        run: yarn dev &  # Start the app in the background

      - name: Wait for App to Be Ready
        run: |
          until curl --output /dev/null --silent --head --fail http://localhost:3000; do
            echo "Waiting for the app to be ready..."
            sleep 5
          done

      - name: Run Cypress Tests
        run: npx cypress run --config baseUrl=http://www.nimblebee.local

  deploy:
    if: success() && (github.event_name == 'workflow_dispatch' || github.ref_name == 'main')
    runs-on: ubuntu-latest
    needs: test  # Only deploy if tests pass

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Zip Artifact for Deployment
        run: (cd ./.next/standalone && zip -r ../../release.zip .)

      - name: Upload Artifact for Deployment
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: release.zip

      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_4405A45699474090BBF161078DF725FB }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_CF2241290AE3402CB767D18D2E330330 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_F63FCF82167448FDAB2D87D1A5A3CCE9 }}

      - name: Upload Static Files to Azure Blob Storage
        run: |
          az storage blob sync -c 'nimblebee-front-static' --account-name nimblebeefrontstorage --account-key ${{ secrets.AZURE_STORAGE_ACCOUNT_KEY }} -s './.next/static' -d '_next/static'
          az storage blob sync -c 'nimblebee-front-static' --account-name nimblebeefrontstorage --account-key ${{ secrets.AZURE_STORAGE_ACCOUNT_KEY }} -s './public' -d 'public'
        continue-on-error: true

      - name: Purge Azure CDN Endpoint
        run: |
          az cdn endpoint purge --content-paths '/*' --profile-name nimblebee-front-cdn --name nimblebee-front-cdn --resource-group nimblebee-front_group
        continue-on-error: true

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'nimblebee-front'
          slot-name: 'Production'
          package: release.zip
