export const KEYS = {
  GET_COURSES: 'GET_COURSES',
  CREATE_COURSE: 'CREATE_COURSE',
  GET_COURSE_DETAILS: 'GET_COURSE_DETAILS',
  GET_INSTRUCTORS: 'GET_INSTRUCTORS',
  CREATE_INSTRUCTOR: 'CREATE_INSTRUCTOR',
  GET_INSTRUCTOR_DETAILS: 'GET_INSTRUCTOR_DETAILS'
}
